---
abstract: "A module to make it simple to drop all privileges, even \nPOSIX groups."
author:
  - 'Troels Liebe Bentsen <troels@infopro.dk>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Privileges-Drop
provides:
  Privileges::Drop:
    file: lib/Privileges/Drop.pm
    version: 1.03
requires:
  Carp: 0
  English: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.03
